# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c5a2179caefe012c707517cebc75aef58060814708b4769c60e9aaac3061e3a7828aed5212138083fd95569a2bbe0f43623808d0004473509ce0e93d7d4ecf

test:
  secret_key_base: 34600aa8afa02001ba13a3b16aee0b6f9f756cc0707cabf5c230260085ab92068e3a53ca96e46da52e6bc177125f9fe0b7e9ad582f3daaaa0332efc97d28aa43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
